sequenceDiagram
    participant CBACT03C
    participant XREFFILE

    activate CBACT03C
    CBACT03C->>+XREFFILE: Open
    XREFFILE-->>-CBACT03C: Open Successful

    loop For Each Record in XREFFILE
        CBACT03C->>+XREFFILE: Read Record
        XREFFILE-->>-CBACT03C: Card Account Cross-Reference Record
        CBACT03C->>CBACT03C: Display Record
    end

    CBACT03C->>+XREFFILE: Close
    XREFFILE-->>-CBACT03C: Close Successful
    deactivate CBACT03C