sequenceDiagram
    participant Main Program
    participant CBSTM03B Subroutine
    participant TRNX-FILE
    participant XREF-FILE
    participant CUST-FILE
    participant ACCT-FILE

    activate Main Program
    Main Program->>+CBSTM03B Subroutine: Open TRNX-FILE
    activate CBSTM03B Subroutine
    CBSTM03B Subroutine->>+TRNX-FILE: Open
    TRNX-FILE->>CBSTM03B Subroutine: Open Successful
    CBSTM03B Subroutine->>Main Program: File Opened
    
    Main Program->>+CBSTM03B Subroutine: Read Record from TRNX-FILE
    CBSTM03B Subroutine->>+TRNX-FILE: Read
    TRNX-FILE->>CBSTM03B Subroutine: Transaction Data
    CBSTM03B Subroutine->>Main Program: Transaction Data

    Main Program->>+CBSTM03B Subroutine: Close TRNX-FILE
    CBSTM03B Subroutine->>+TRNX-FILE: Close
    TRNX-FILE-->>-CBSTM03B Subroutine: Close Successful
    deactivate TRNX-FILE
    CBSTM03B Subroutine->>Main Program: File Closed
    deactivate CBSTM03B Subroutine
    deactivate Main Program