sequenceDiagram
    participant CBACT01C
    participant ACCTFILE

    activate CBACT01C
    CBACT01C->>+ACCTFILE: Open
    ACCTFILE-->>-CBACT01C: Open Successful
    loop For Each Record in ACCTFILE
        CBACT01C->>+ACCTFILE: Read Record
        ACCTFILE-->>-CBACT01C: Account Record Data
        CBACT01C->>CBACT01C: Display Record Details
    end
    CBACT01C->>+ACCTFILE: Close
    ACCTFILE->>-CBACT01C: Close Successful
    deactivate CBACT01C