sequenceDiagram
    participant CBTRN03C
    participant TRANSACTFILE
    participant XREFFILE
    participant TRANTYPEFILE
    participant TRANCATGFILE
    participant DATEPARMSFILE
    participant REPORTFILE

    activate CBTRN03C
    CBTRN03C->>+TRANSACTFILE: Open
    TRANSACTFILE-->>-CBTRN03C: Open Successful
    CBTRN03C->>+XREFFILE: Open
    XREFFILE-->>-CBTRN03C: Open Successful
    CBTRN03C->>+TRANTYPEFILE: Open
    TRANTYPEFILE-->>-CBTRN03C: Open Successful
    CBTRN03C->>+TRANCATGFILE: Open
    TRANCATGFILE-->>-CBTRN03C: Open Successful
    CBTRN03C->>+DATEPARMSFILE: Open
    DATEPARMSFILE-->>-CBTRN03C: Open Successful
    CBTRN03C->>+REPORTFILE: Open
    REPORTFILE-->>-CBTRN03C: Open Successful

    CBTRN03C->>+DATEPARMSFILE: Read Start Date/End Date
    DATEPARMSFILE-->>-CBTRN03C: Start Date/End Date

    loop For Each Transaction in TRANSACTFILE
        CBTRN03C->>+TRANSACTFILE: Read Transaction Record
        TRANSACTFILE-->>-CBTRN03C: Transaction Record
        
        alt Transaction Date Within Range
            CBTRN03C->>+XREFFILE: Read Account Details
            XREFFILE-->>-CBTRN03C: Account Details
            CBTRN03C->>+TRANTYPEFILE: Read Transaction Type Description
            TRANTYPEFILE-->>-CBTRN03C: Transaction Type Description
            CBTRN03C->>+TRANCATGFILE: Read Transaction Category Description
            TRANCATGFILE-->>-CBTRN03C: Transaction Category Description
            CBTRN03C->>+REPORTFILE: Write Transaction Detail to Report
            REPORTFILE-->>-CBTRN03C: Write Successful
        end
    end

    CBTRN03C->>+REPORTFILE: Close
    REPORTFILE->>-CBTRN03C: Close Successful
    CBTRN03C->>+DATEPARMSFILE: Close
    DATEPARMSFILE->>-CBTRN03C: Close Successful
    CBTRN03C->>+TRANCATGFILE: Close
    TRANCATGFILE->>-CBTRN03C: Close Successful
    CBTRN03C->>+TRANTYPEFILE: Close
    TRANTYPEFILE->>-CBTRN03C: Close Successful
    CBTRN03C->>+XREFFILE: Close
    XREFFILE->>-CBTRN03C: Close Successful
    CBTRN03C->>+TRANSACTFILE: Close
    TRANSACTFILE->>-CBTRN03C: Close Successful
    deactivate CBTRN03C