sequenceDiagram
    participant User
    participant COCRDSLC
    participant CARDDAT
    
    activate User
    User->>+COCRDSLC: Input Account or Card Number
    activate COCRDSLC
    COCRDSLC->>+CARDDAT: Read Card Data
    activate CARDDAT
    alt Card Found
        CARDDAT->>COCRDSLC: Card Record
        COCRDSLC->>User: Display Card Details
    else Card Not Found
        CARDDAT->>COCRDSLC: Not Found
        COCRDSLC->>User: Display Error Message
    end
    deactivate CARDDAT
    deactivate COCRDSLC
    deactivate User