sequenceDiagram
    participant User
    participant COMEN01C
    participant Program Module

    activate COMEN01C
    COMEN01C->>+User: Display Main Menu
    User-->>-COMEN01C: Select Option
    COMEN01C->>COMEN01C: Validate Option
    alt Valid Option
        COMEN01C->>+Program Module: Transfer Control 
                activate Program Module
        Program Module->>User: Display Screen/Perform Action
        deactivate Program Module
    else Invalid Option
        COMEN01C->>-User: Display Error Message
    end