sequenceDiagram
    participant CallingProgram
    participant CSUTLDTC
    participant CEEDAYS
    
    activate CallingProgram
    CallingProgram->>+CSUTLDTC: LS-DATE, LS-DATE-FORMAT
    activate CSUTLDTC
    CSUTLDTC->>+CEEDAYS: WS-DATE-TO-TEST, WS-DATE-FORMAT
    activate CEEDAYS
    CEEDAYS->>CSUTLDTC: OUTPUT-LILLIAN, FEEDBACK-CODE
    deactivate CEEDAYS
    CSUTLDTC->>CallingProgram: LS-RESULT
    deactivate CSUTLDTC
    deactivate CallingProgram