sequenceDiagram
    participant Administrator
    participant COADM02Y
    participant COUSR00C
    participant COUSR01C
    participant COUSR02C
    participant COUSR03C

    activate Administrator
    Administrator->>+COADM02Y: Select Menu Option (1-4)
    COADM02Y->>-Administrator: Display User Management Menu

    alt User List
        Administrator->>+COADM02Y: 1
        COADM02Y->>+COUSR00C: Execute User List
        deactivate COUSR00C
    else User Add
        Administrator->>+COADM02Y: 2
        COADM02Y->>+COUSR01C: Execute User Add
        deactivate COUSR01C
    else User Update
        Administrator->>+COADM02Y: 3
        COADM02Y->>+COUSR02C: Execute User Update
        deactivate COUSR02C
    else User Delete
        Administrator->>+COADM02Y: 4
        COADM02Y->>+COUSR03C: Execute User Delete
        deactivate COUSR03C
    end

    deactivate Administrator
    deactivate COADM02Y