sequenceDiagram
    participant Administrator
    participant CardDemo Application
    participant Admin Menu Program

    Administrator->>+CardDemo Application: Request Admin Menu
    activate CardDemo Application
    CardDemo Application->>+Admin Menu Program: Execute
    activate Admin Menu Program
    Admin Menu Program->>CardDemo Application: Menu Options
    CardDemo Application->>Administrator: Display Admin Menu
    Administrator->>+CardDemo Application: Select Menu Option (Number)
    CardDemo Application->>+Admin Menu Program: Validate User Type and Option
    alt Valid User and Option
        CardDemo Application->>+Corresponding Program: Execute Selected Program
                    else Invalid User or Option
        Admin Menu Program->>-CardDemo Application: Invalid Selection
        CardDemo Application->>-Administrator: Display Error Message
    end