sequenceDiagram
    participant Program A
    participant Program B
    participant CARDDEMO-COMMAREA

    activate Program A
    Program A->>+Program B: Execute Program B
    activate Program B
    Program A->>+CARDDEMO-COMMAREA: Populate Data
    Program A->>CARDDEMO-COMMAREA: Data Populated
    Program A->>Program B: Data is ready in CARDDEMO-COMMAREA
    Program B->>+CARDDEMO-COMMAREA: Read Data
    Program B->>CARDDEMO-COMMAREA: Data Retrieved
    Program B->>Program A: Finish execution
    deactivate Program B
    deactivate Program A