sequenceDiagram
    participant User 
    participant ProgramA
    participant CVCRD01Y
    participant ProgramB

    User->>+ProgramA: Input data
    activate ProgramA
    ProgramA->>+CVCRD01Y: Store Data
    activate CVCRD01Y
    CVCRD01Y-->>-ProgramA: Data Stored
    ProgramA->>+ProgramB: Access Data
    activate ProgramB
    ProgramB->>+CVCRD01Y: Retrieve Data
    CVCRD01Y->>ProgramB: Data Retrieved
    ProgramB->>ProgramA: Data Processed
    deactivate ProgramB
    deactivate CVCRD01Y
    ProgramA->>User: Display Result
    deactivate ProgramA