sequenceDiagram
    participant Credit Card Processing System
    participant Card XREF File

    activate Credit Card Processing System
    Credit Card Processing System->>+Card XREF File: Open
    Card XREF File->>Credit Card Processing System: File Opened

    Credit Card Processing System->>+Card XREF File: Read Record (Card Number)
    Card XREF File->>Credit Card Processing System:  Card Number, Customer ID, Account ID
    deactivate Card XREF File
    deactivate Credit Card Processing System