sequenceDiagram
  participant AccountManagementProgram
  participant COACTUPCopybook
  participant VSAMAccountFile

  activate AccountManagementProgram
  AccountManagementProgram->>+COACTUPCopybook: Carregar estrutura de dados da conta
  COACTUPCopybook-->>-AccountManagementProgram: Estrutura de dados da conta carregada

  AccountManagementProgram->>+VSAMAccountFile: Ler registro da conta (usando ACCTSIDI)
  VSAMAccountFile-->>-AccountManagementProgram: Dados do registro da conta

  AccountManagementProgram->>AccountManagementProgram: Preencher a estrutura de dados COACTUP com os dados da conta existentes e informações de atualização.

  alt Validação bem-sucedida
    AccountManagementProgram->>+VSAMAccountFile: Atualizar registro da conta
    VSAMAccountFile-->>-AccountManagementProgram: Atualização bem-sucedida
  else Validação falhou
    AccountManagementProgram->>AccountManagementProgram: Registrar erro (dados inválidos)
  end
  deactivate AccountManagementProgram