sequenceDiagram
    participant Application
    participant COCRDLI
    
    activate Application
    Application->>+COCRDLI: Read Credit Card Data Layout
    COCRDLI-->>-Application: Data Structure Definitions (CCRDLIAI, CCRDLIAO)
    deactivate Application