sequenceDiagram
    participant Administrator
    participant COUSR00 Data Structure
    participant User Management Program

    activate Administrator
    Administrator->>+User Management Program: Request User List
    activate User Management Program
    User Management Program->>+COUSR00 Data Structure: Populate Data
    activate COUSR00 Data Structure
    COUSR00 Data Structure->>User Management Program:  Data Populated
    User Management Program->>Administrator: Display User List
    deactivate COUSR00 Data Structure
    deactivate User Management Program