sequenceDiagram
    participant COBOL Program
    participant User Information Data

    activate COBOL Program
    COBOL Program->>+User Information Data: Access User Data (COUSR01)
    User Information Data-->>-COBOL Program: User Data Structure (COUSR1AI or COUSR1AO)
    deactivate COBOL Program