classDiagram
    COSGN00C --|> COMEN01C
    COSGN00C --|> COADM01C
    COMEN01C --|> COACTVWC
    COMEN01C --|> COCRDLIC
    COMEN01C --|> COTRN00C
    COMEN01C --|> COBIL00C
    COMEN01C --|> CORPT00C
    COADM01C --|> COUSR00C
    COCRDLIC --|> COCRDSLC
    COCRDSLC --|> COCRDUPC
    COTRN00C --|> COTRN01C
    COTRN00C --|> COTRN02C
    COUSR00C --|> COUSR01C
    COUSR00C --|> COUSR02C
    COUSR00C --|> COUSR03C
    CBSTM03A --|> CBSTM03B
    CBACT01C --|> VSAM_ACCTFILE
    CBACT02C --|> VSAM_CARDFILE
    CBACT03C --|> VSAM_XREFFILE
    CBACT04C --|> VSAM_TCATBALF
    CBACT04C --|> VSAM_XREFFILE
    CBACT04C --|> VSAM_DISCGRP
    CBACT04C --|> VSAM_ACCTFILE
    CBACT04C --|> VSAM_TRANFILE
    CBCUS01C --|> VSAM_CUSTFILE
    CBSTM03A --|> VSAM_XREFFILE
    CBSTM03A --|> VSAM_CUSTFILE
    CBSTM03A --|> VSAM_ACCTFILE
    CBSTM03A --|> VSAM_TRNXFILE
    CBSTM03B --|> VSAM_TRNXFILE
    CBSTM03B --|> VSAM_XREFFILE
    CBSTM03B --|> VSAM_CUSTFILE
    CBSTM03B --|> VSAM_ACCTFILE
    CBTRN01C --|> VSAM_DALYTRAN
    CBTRN01C --|> VSAM_CUSTFILE
    CBTRN01C --|> VSAM_XREFFILE
    CBTRN01C --|> VSAM_CARDFILE
    CBTRN01C --|> VSAM_ACCTFILE
    CBTRN01C --|> VSAM_TRANFILE
    CBTRN02C --|> VSAM_DALYTRAN
    CBTRN02C --|> VSAM_TRANFILE
    CBTRN02C --|> VSAM_XREFFILE
    CBTRN02C --|> VSAM_DALYREJS
    CBTRN02C --|> VSAM_ACCTFILE
    CBTRN02C --|> VSAM_TCATBALF
    CBTRN03C --|> VSAM_TRANFILE
    CBTRN03C --|> VSAM_REPTFILE
    CBTRN03C --|> VSAM_CARDXREF
    CBTRN03C --|> VSAM_TRANTYPE
    CBTRN03C --|> VSAM_TRANCATG
    CBTRN03C --|> VSAM_DATEPARM
    COACTUPC --|> VSAM_ACCTMAST
    COACTUPC --|> VSAM_CUSTMAST
    COACTUPC --|> VSAM_CARDDAT
    COACTVWC --|> VSAM_CARDXREF
    COACTVWC --|> VSAM_ACCTDAT
    COACTVWC --|> VSAM_CUSTDAT
    COBIL00C --|> VSAM_ACCTDAT
    COBIL00C --|> VSAM_CXACAIX
    COBIL00C --|> VSAM_TRANSACT
    COCRDLIC --|> VSAM_CARDDAT
    COCRDLIC --|> VSAM_CARDAIX
    COCRDSLC --|> VSAM_CARDDAT
    COCRDSLC --|> VSAM_CARDAIX
    COCRDUPC --|> VSAM_CARDDAT
    COSGN00C --|> VSAM_USRSEC
    COTRN00C --|> VSAM_TRANSACT
    COTRN01C --|> VSAM_TRANSACT
    COTRN02C --|> VSAM_TRANSACT
    COTRN02C --|> VSAM_ACCTDAT
    COTRN02C --|> VSAM_CCXREF
    COTRN02C --|> VSAM_CXACAIX
    COUSR00C --|> VSAM_USRSEC
    COUSR01C --|> VSAM_USRSEC
    COUSR02C --|> VSAM_USRSEC
    COUSR03C --|> VSAM_USRSEC
    CSUTLDTC --|> CEEDAYS
    class CBACT01C["CBACT01C"]{
      +0000-ACCTFILE-OPEN()
      +1000-ACCTFILE-GET-NEXT()
      +1100-DISPLAY-ACCT-RECORD()
      +9000-ACCTFILE-CLOSE()
      +9999-ABEND-PROGRAM()
      +9910-DISPLAY-IO-STATUS()
    }
    class CBACT02C["CBACT02C"]{
    }
    class CBACT03C["CBACT03C"]{
      +0000-XREFFILE-OPEN()
      +1000-XREFFILE-GET-NEXT()
      +9000-XREFFILE-CLOSE()
      +9999-ABEND-PROGRAM()
      +9910-DISPLAY-IO-STATUS()
    }
    class CBACT04C["CBACT04C"]{
      +0000-TCATBALF-OPEN()
      +0100-XREFFILE-OPEN()
      +0200-DISCGRP-OPEN()
      +0300-ACCTFILE-OPEN()
      +0400-TRANFILE-OPEN()
      +1000-TCATBALF-GET-NEXT()
      +1050-UPDATE-ACCOUNT()
      +1100-GET-ACCT-DATA()
      +1110-GET-XREF-DATA()
      +1200-GET-INTEREST-RATE()
      +1200-A-GET-DEFAULT-INT-RATE()
      +1300-COMPUTE-INTEREST()
      +1300-B-WRITE-TX()
      +1400-COMPUTE-FEES()
      +9000-TCATBALF-CLOSE()
      +9100-XREFFILE-CLOSE()
      +9200-DISCGRP-CLOSE()
      +9300-ACCTFILE-CLOSE()
      +9400-TRANFILE-CLOSE()
      +Z-GET-DB2-FORMAT-TIMESTAMP()
      +9999-ABEND-PROGRAM()
      +9910-DISPLAY-IO-STATUS()
    }
    class CBCUS01C["CBCUS01C"]{
      +0000-CUSTFILE-OPEN()
      +1000-CUSTFILE-GET-NEXT()
      +9000-CUSTFILE-CLOSE()
      +Z-ABEND-PROGRAM()
      +Z-DISPLAY-IO-STATUS()
    }
    class CBSTM03A["CBSTM03A"]{
      +0000-START()
      +1000-MAINLINE()
      +1000-XREFFILE-GET-NEXT()
      +2000-CUSTFILE-GET()
      +3000-ACCTFILE-GET()
      +4000-TRNXFILE-GET()
      +5000-CREATE-STATEMENT()
      +5100-WRITE-HTML-HEADER()
      +5100-EXIT()
      +5200-WRITE-HTML-NMADBS()
      +5200-EXIT()
      +6000-WRITE-TRANS()
      +8100-FILE-OPEN()
      +8100-TRNXFILE-OPEN()
      +8200-XREFFILE-OPEN()
      +8300-CUSTFILE-OPEN()
      +8400-ACCTFILE-OPEN()
      +8500-READTRNX-READ()
      +8599-EXIT()
      +9100-TRNXFILE-CLOSE()
      +9200-XREFFILE-CLOSE()
      +9300-CUSTFILE-CLOSE()
      +9400-ACCTFILE-CLOSE()
      +9999-GOBACK()
      +9999-ABEND-PROGRAM()
    }
    class CBSTM03B["CBSTM03B"]{
      +0000-START()
      +9999-GOBACK()
      +1000-TRNXFILE-PROC()
      +1900-EXIT()
      +1999-EXIT()
      +2000-XREFFILE-PROC()
      +2900-EXIT()
      +2999-EXIT()
      +3000-CUSTFILE-PROC()
      +3900-EXIT()
      +3999-EXIT()
      +4000-ACCTFILE-PROC()
      +4900-EXIT()
      +4999-EXIT()
    }
    class CBTRN01C["CBTRN01C"]{
      +0000-DALYTRAN-OPEN()
      +0100-CUSTFILE-OPEN()
      +0200-XREFFILE-OPEN()
      +0300-CARDFILE-OPEN()
      +0400-ACCTFILE-OPEN()
      +0500-TRANFILE-OPEN()
      +1000-DALYTRAN-GET-NEXT()
      +2000-LOOKUP-XREF()
      +3000-READ-ACCOUNT()
      +9000-DALYTRAN-CLOSE()
      +9100-CUSTFILE-CLOSE()
      +9200-XREFFILE-CLOSE()
      +9300-CARDFILE-CLOSE()
      +9400-ACCTFILE-CLOSE()
      +9500-TRANFILE-CLOSE()
      +Z-ABEND-PROGRAM()
      +Z-DISPLAY-IO-STATUS()
    }
    class CBTRN02C["CBTRN02C"]{
      +0000-DALYTRAN-OPEN()
      +0100-TRANFILE-OPEN()
      +0200-XREFFILE-OPEN()
      +0300-DALYREJS-OPEN()
      +0400-ACCTFILE-OPEN()
      +0500-TCATBALF-OPEN()
      +1000-DALYTRAN-GET-NEXT()
      +1500-VALIDATE-TRAN()
      +1500-A-LOOKUP-XREF()
      +1500-B-LOOKUP-ACCT()
      +2000-POST-TRANSACTION()
      +2500-WRITE-REJECT-REC()
      +2700-UPDATE-TCATBAL()
      +2700-A-CREATE-TCATBAL-REC()
      +2700-B-UPDATE-TCATBAL-REC()
      +2800-UPDATE-ACCOUNT-REC()
      +2900-WRITE-TRANSACTION-FILE()
      +9000-DALYTRAN-CLOSE()
      +9100-TRANFILE-CLOSE()
      +9200-XREFFILE-CLOSE()
      +9300-DALYREJS-CLOSE()
      +9400-ACCTFILE-CLOSE()
      +9500-TCATBALF-CLOSE()
      +Z-GET-DB2-FORMAT-TIMESTAMP()
      +9999-ABEND-PROGRAM()
      +9910-DISPLAY-IO-STATUS()
    }
    class CBTRN03C["CBTRN03C"]{
      +0000-TRANFILE-OPEN()
      +0100-REPTFILE-OPEN()
      +0200-CARDXREF-OPEN()
      +0300-TRANTYPE-OPEN()
      +0400-TRANCATG-OPEN()
      +0500-DATEPARM-OPEN()
      +0550-DATEPARM-READ()
      +1000-TRANFILE-GET-NEXT()
      +1100-WRITE-TRANSACTION-REPORT()
      +1110-WRITE-PAGE-TOTALS()
      +1120-WRITE-ACCOUNT-TOTALS()
      +1110-WRITE-GRAND-TOTALS()
      +1120-WRITE-HEADERS()
      +1111-WRITE-REPORT-REC()
      +1120-WRITE-DETAIL()
      +1500-A-LOOKUP-XREF()
      +1500-B-LOOKUP-TRANTYPE()
      +1500-C-LOOKUP-TRANCATG()
      +9000-TRANFILE-CLOSE()
      +9100-REPTFILE-CLOSE()
      +9200-CARDXREF-CLOSE()
      +9300-TRANTYPE-CLOSE()
      +9400-TRANCATG-CLOSE()
      +9500-DATEPARM-CLOSE()
      +9999-ABEND-PROGRAM()
      +9910-DISPLAY-IO-STATUS()
    }
    class COACTUPC["COACTUPC"]{
      +0000-MAIN()
      +COMMON-RETURN()
      +0000-MAIN-EXIT()
      +1000-PROCESS-INPUTS()
      +1100-RECEIVE-MAP()
      +1200-EDIT-MAP-INPUTS()
      +1205-COMPARE-OLD-NEW()
      +1210-EDIT-ACCOUNT()
      +1215-EDIT-MANDATORY()
      +1220-EDIT-YESNO()
      +1225-EDIT-ALPHA-REQD()
      +1230-EDIT-ALPHANUM-REQD()
      +1235-EDIT-ALPHA-OPT()
      +1240-EDIT-ALPHANUM-OPT()
      +1245-EDIT-NUM-REQD()
      +1250-EDIT-SIGNED-9V2()
      +1260-EDIT-US-PHONE-NUM()
      +EDIT-AREA-CODE()
      +EDIT-US-PHONE-PREFIX()
      +EDIT-US-PHONE-LINENUM()
      +EDIT-US-PHONE-EXIT()
      +1265-EDIT-US-SSN()
      +1270-EDIT-US-STATE-CD()
      +1275-EDIT-FICO-SCORE()
      +1280-EDIT-US-STATE-ZIP-CD()
      +2000-DECIDE-ACTION()
      +3000-SEND-MAP()
      +3100-SCREEN-INIT()
      +3200-SETUP-SCREEN-VARS()
      +3201-SHOW-INITIAL-VALUES()
      +3202-SHOW-ORIGINAL-VALUES()
      +3203-SHOW-UPDATED-VALUES()
      +3250-SETUP-INFOMSG()
      +3300-SETUP-SCREEN-ATTRS()
      +3310-PROTECT-ALL-ATTRS()
      +3320-UNPROTECT-FEW-ATTRS()
      +3390-SETUP-INFOMSG-ATTRS()
      +3400-SEND-SCREEN()
      +9000-READ-ACCT()
      +9200-GETCARDXREF-BYACCT()
      +9300-GETACCTDATA-BYACCT()
      +9400-GETCUSTDATA-BYCUST()
      +9500-STORE-FETCHED-DATA()
      +9600-WRITE-PROCESSING()
      +9700-CHECK-CHANGE-IN-REC()
      +ABEND-ROUTINE()
      +EDIT-DATE-CCYYMMDD()
      +EDIT-DATE-OF-BIRTH()
    }
    class COACTVWC["COACTVWC"]{
      +0000-MAIN()
      +1000-SEND-MAP()
      +1100-SCREEN-INIT()
      +1200-SETUP-SCREEN-VARS()
      +1300-SETUP-SCREEN-ATTRS()
      +1400-SEND-SCREEN()
      +2000-PROCESS-INPUTS()
      +2100-RECEIVE-MAP()
      +2200-EDIT-MAP-INPUTS()
      +2210-EDIT-ACCOUNT()
      +9000-READ-ACCT()
      +9200-GETCARDXREF-BYACCT()
      +9300-GETACCTDATA-BYACCT()
      +9400-GETCUSTDATA-BYCUST()
      +SEND-PLAIN-TEXT()
      +SEND-LONG-TEXT()
      +ABEND-ROUTINE()
    }
    class COADM01C["COADM01C"]{
      +MAIN-PARA()
      +PROCESS-ENTER-KEY()
      +RETURN-TO-SIGNON-SCREEN()
      +SEND-MENU-SCREEN()
      +RECEIVE-MENU-SCREEN()
      +POPULATE-HEADER-INFO()
      +BUILD-MENU-OPTIONS()
    }
    class COBIL00C["COBIL00C"]{
      +MAIN-PARA()
      +PROCESS-ENTER-KEY()
      +GET-CURRENT-TIMESTAMP()
      +RETURN-TO-PREV-SCREEN()
      +SEND-BILLPAY-SCREEN()
      +RECEIVE-BILLPAY-SCREEN()
      +POPULATE-HEADER-INFO()
      +READ-ACCTDAT-FILE()
      +UPDATE-ACCTDAT-FILE()
      +READ-CXACAIX-FILE()
      +STARTBR-TRANSACT-FILE()
      +READPREV-TRANSACT-FILE()
      +ENDBR-TRANSACT-FILE()
      +WRITE-TRANSACT-FILE()
      +CLEAR-CURRENT-SCREEN()
      +INITIALIZE-ALL-FIELDS()
    }
    class COCRDLIC["COCRDLIC"]{
      +0000-MAIN()
      +COMMON-RETURN()
      +1000-SEND-MAP()
      +1100-SCREEN-INIT()
      +1200-SCREEN-ARRAY-INIT()
      +1250-SETUP-ARRAY-ATTRIBS()
      +1300-SETUP-SCREEN-ATTRS()
      +1400-SETUP-MESSAGE()
      +1500-SEND-SCREEN()
      +2000-RECEIVE-MAP()
      +2100-RECEIVE-SCREEN()
      +2200-EDIT-INPUTS()
      +2210-EDIT-ACCOUNT()
      +2220-EDIT-CARD()
      +2250-EDIT-ARRAY()
      +9000-READ-FORWARD()
      +9100-READ-BACKWARDS()
      +9500-FILTER-RECORDS()
      +SEND-PLAIN-TEXT()
      +SEND-LONG-TEXT()
    }
    class COCRDSLC["COCRDSLC"]{
      +0000-MAIN()
      +COMMON-RETURN()
      +1000-SEND-MAP()
      +1100-SCREEN-INIT()
      +1200-SETUP-SCREEN-VARS()
      +1300-SETUP-SCREEN-ATTRS()
      +1400-SEND-SCREEN()
      +2000-PROCESS-INPUTS()
      +2100-RECEIVE-MAP()
      +2200-EDIT-MAP-INPUTS()
      +2210-EDIT-ACCOUNT()
      +2220-EDIT-CARD()
      +9000-READ-DATA()
      +9100-GETCARD-BYACCTCARD()
      +9150-GETCARD-BYACCT()
      +SEND-LONG-TEXT()
      +SEND-PLAIN-TEXT()
      +ABEND-ROUTINE()
    }
    class COCRDUPC["COCRDUPC"]{
      +0000-MAIN()
      +YYYY-STORE-PFKEY()
      +9000-READ-DATA()
      +9100-GETCARD-BYACCTCARD()
      +9200-WRITE-PROCESSING()
      +9300-CHECK-CHANGE-IN-REC()
      +1000-PROCESS-INPUTS()
      +1100-RECEIVE-MAP()
      +1200-EDIT-MAP-INPUTS()
      +1210-EDIT-ACCOUNT()
      +1220-EDIT-CARD()
      +1230-EDIT-NAME()
      +1240-EDIT-CARDSTATUS()
      +1250-EDIT-EXPIRY-MON()
      +1260-EDIT-EXPIRY-YEAR()
      +2000-DECIDE-ACTION()
      +3000-SEND-MAP()
      +3100-SCREEN-INIT()
      +3200-SETUP-SCREEN-VARS()
      +3250-SETUP-INFOMSG()
      +3300-SETUP-SCREEN-ATTRS()
      +3400-SEND-SCREEN()
      +ABEND-ROUTINE()
    }
    class COMEN01C["COMEN01C"]{
      +MAIN-PARA()
      +PROCESS-ENTER-KEY()
      +RETURN-TO-SIGNON-SCREEN()
      +SEND-MENU-SCREEN()
      +RECEIVE-MENU-SCREEN()
      +POPULATE-HEADER-INFO()
      +BUILD-MENU-OPTIONS()
    }
    class CORPT00C["CORPT00C"]{
      +MAIN-PARA()
      +PROCESS-ENTER-KEY()
      +SUBMIT-JOB-TO-INTRDR()
      +WIRTE-JOBSUB-TDQ()
      +RETURN-TO-PREV-SCREEN()
      +SEND-TRNRPT-SCREEN()
      +RETURN-TO-CICS()
      +RECEIVE-TRNRPT-SCREEN()
      +POPULATE-HEADER-INFO()
      +INITIALIZE-ALL-FIELDS()
    }
    class COSGN00C["COSGN00C"]{
      +MAIN-PARA()
      +PROCESS-ENTER-KEY()
      +SEND-SIGNON-SCREEN()
      +SEND-PLAIN-TEXT()
      +POPULATE-HEADER-INFO()
      +READ-USER-SEC-FILE()
    }
    class COTRN00C["COTRN00C"]{
      +MAIN-PARA()
      +PROCESS-ENTER-KEY()
      +PROCESS-PF7-KEY()
      +PROCESS-PF8-KEY()
      +PROCESS-PAGE-FORWARD()
      +PROCESS-PAGE-BACKWARD()
      +POPULATE-TRAN-DATA()
      +INITIALIZE-TRAN-DATA()
      +RETURN-TO-PREV-SCREEN()
      +SEND-TRNLST-SCREEN()
      +RECEIVE-TRNLST-SCREEN()
      +POPULATE-HEADER-INFO()
      +STARTBR-TRANSACT-FILE()
      +READNEXT-TRANSACT-FILE()
      +READPREV-TRANSACT-FILE()
      +ENDBR-TRANSACT-FILE()
    }
    class COTRN01C["COTRN01C"]{
      +MAIN-PARA()
      +PROCESS-ENTER-KEY()
      +RETURN-TO-PREV-SCREEN()
      +SEND-TRNVIEW-SCREEN()
      +RECEIVE-TRNVIEW-SCREEN()
      +POPULATE-HEADER-INFO()
      +READ-TRANSACT-FILE()
      +CLEAR-CURRENT-SCREEN()
      +INITIALIZE-ALL-FIELDS()
    }
    class COTRN02C["COTRN02C"]{
      +MAIN-PARA()
      +PROCESS-ENTER-KEY()
      +VALIDATE-INPUT-KEY-FIELDS()
      +VALIDATE-INPUT-DATA-FIELDS()
      +ADD-TRANSACTION()
      +COPY-LAST-TRAN-DATA()
      +RETURN-TO-PREV-SCREEN()
      +SEND-TRNADD-SCREEN()
      +RECEIVE-TRNADD-SCREEN()
      +POPULATE-HEADER-INFO()
      +READ-CXACAIX-FILE()
      +READ-CCXREF-FILE()
      +STARTBR-TRANSACT-FILE()
      +READPREV-TRANSACT-FILE()
      +ENDBR-TRANSACT-FILE()
      +WRITE-TRANSACT-FILE()
      +CLEAR-CURRENT-SCREEN()
      +INITIALIZE-ALL-FIELDS()
    }
    class COUSR00C["COUSR00C"]{
    }
    class COUSR01C["COUSR01C"]{
      +MAIN-PARA()
      +PROCESS-ENTER-KEY()
      +RETURN-TO-PREV-SCREEN()
      +SEND-USRADD-SCREEN()
      +RECEIVE-USRADD-SCREEN()
      +POPULATE-HEADER-INFO()
      +WRITE-USER-SEC-FILE()
      +CLEAR-CURRENT-SCREEN()
      +INITIALIZE-ALL-FIELDS()
    }
    class COUSR02C["COUSR02C"]{
      +MAIN-PARA()
      +PROCESS-ENTER-KEY()
      +UPDATE-USER-INFO()
      +RETURN-TO-PREV-SCREEN()
      +SEND-USRUPD-SCREEN()
      +RECEIVE-USRUPD-SCREEN()
      +POPULATE-HEADER-INFO()
      +READ-USER-SEC-FILE()
      +UPDATE-USER-SEC-FILE()
      +CLEAR-CURRENT-SCREEN()
      +INITIALIZE-ALL-FIELDS()
    }
    class COUSR03C["COUSR03C"]{
      +MAIN-PARA()
      +PROCESS-ENTER-KEY()
      +DELETE-USER-INFO()
      +RETURN-TO-PREV-SCREEN()
      +SEND-USRDEL-SCREEN()
      +RECEIVE-USRDEL-SCREEN()
      +POPULATE-HEADER-INFO()
      +READ-USER-SEC-FILE()
      +DELETE-USER-SEC-FILE()
      +CLEAR-CURRENT-SCREEN()
      +INITIALIZE-ALL-FIELDS()
    }
    class CSUTLDTC["CSUTLDTC"]{
      +A000-MAIN()
      +A000-MAIN-EXIT()
    }
    class CEEDAYS["CEEDAYS"]{
    }
    class VSAM_ACCTFILE["VSAM_ACCTFILE"]{
    }
    class VSAM_CARDFILE["VSAM_CARDFILE"]{
    }
    class VSAM_XREFFILE["VSAM_XREFFILE"]{
    }
    class VSAM_TCATBALF["VSAM_TCATBALF"]{
    }
    class VSAM_TRANFILE["VSAM_TRANFILE"]{
    }
    class VSAM_CUSTFILE["VSAM_CUSTFILE"]{
    }
    class VSAM_TRNXFILE["VSAM_TRNXFILE"]{
    }
    class VSAM_DALYTRAN["VSAM_DALYTRAN"]{
    }
    class VSAM_DALYREJS["VSAM_DALYREJS"]{
    }
    class VSAM_REPTFILE["VSAM_REPTFILE"]{
    }
    class VSAM_CARDXREF["VSAM_CARDXREF"]{
    }
    class VSAM_TRANTYPE["VSAM_TRANTYPE"]{
    }
    class VSAM_TRANCATG["VSAM_TRANCATG"]{
    }
    class VSAM_DATEPARM["VSAM_DATEPARM"]{
    }
    class VSAM_ACCTMAST["VSAM_ACCTMAST"]{
    }
    class VSAM_CUSTMAST["VSAM_CUSTMAST"]{
    }
    class VSAM_CARDDAT["VSAM_CARDDAT"]{
    }
    class VSAM_CARDAIX["VSAM_CARDAIX"]{
    }
    class VSAM_USRSEC["VSAM_USRSEC"]{
    }
    class VSAM_ACCTDAT["VSAM_ACCTDAT"]{
    }
    class VSAM_CUSTDAT["VSAM_CUSTDAT"]{
    }
    class VSAM_CXACAIX["VSAM_CXACAIX"]{
    }
    class VSAM_CCXREF["VSAM_CCXREF"]{
    }