graph LR
    classDef diagram stroke:Orange, stroke-width:2px;
    classDef markdown stroke:DodgerBlue, stroke-width:2px;
    classDef epic stroke:DarkOrchid, stroke-width:2px;
    classDef mix stroke:Green, stroke-width:2px;    

    subgraph DOC
        subgraph 05-TECH-STORY
            TechStoryFile(TechStoryFiles.md)
            class TechStoryFile mix;
        end
        subgraph 04-USER-STORY
            UserStoryFile(UserStoryFiles.md)
            class UserStoryFile mix;
        end
        subgraph 03-EPIC
            Epic(Epic.md)
            class Epic epic;
        end
        subgraph 02-DOCUMENT
            DocumentFile(DocumentFiles.md)
            class DocumentFile markdown;
        end
        subgraph 01-UNDERSTAND_CODE
            UnderstandCodeFile(UnderstandCodeFiles.md)
            class UnderstandCodeFile markdown;
        end
    end

    subgraph PROJECT
        subgraph DIAGRAM
            C4Model(C4Model.md)
            Class(Class.md)
            Impact(Impact.md)
            Sequence(Sequence.md)
            class C4Model,Class,Impact,Sequence diagram;
        end

        subgraph REVIEW
            ReviewFile(ReviewFiles.md)
            class ReviewFile markdown;
        end

        subgraph General
            Technology(Technology.md)
            Overview(Overview.md)
        end
        
        class Overview,Technology markdown;
        
    end

    Technology --> Overview

    General ==> DIAGRAM
    General ==> DOC

    REVIEW --> 01-UNDERSTAND_CODE
    01-UNDERSTAND_CODE --> 02-DOCUMENT

    02-DOCUMENT --> 03-EPIC

    01-UNDERSTAND_CODE --> 04-USER-STORY
    02-DOCUMENT --> 04-USER-STORY
    03-EPIC --> 04-USER-STORY

    03-EPIC --> 05-TECH-STORY
    02-DOCUMENT --> 05-TECH-STORY
    01-UNDERSTAND_CODE --> 05-TECH-STORY