sequenceDiagram
    %%Indicates the Participants involved in the process
    participant CBACT02C
    participant CARDFILE

    activate CBACT02C
    CBACT02C->>+CARDFILE: Open
    alt Open Successful
        CARDFILE->>-CBACT02C: Open Successful
        loop For Each Record in CARDFILE
            CBACT02C->>+CARDFILE: Read Record
            alt Read Successful
                CARDFILE->>CBACT02C: Credit Card Record Data
                CBACT02C->>CBACT02C: Display Record
            else Read Error
                CARDFILE->>-CBACT02C: Read Error
                CBACT02C->>CBACT02C: Display Error Message
                CBACT02C->>+CARDFILE: Close
                CARDFILE->>-CBACT02C: Close Successful
                            end
        end
        CBACT02C->>+CARDFILE: Close
        CARDFILE->>CBACT02C: Close Successful
            else Open Error
        CARDFILE->>-CBACT02C: Open Error
        CBACT02C->>CBACT02C: Display Error Message
        deactivate CBACT02C
    end