sequenceDiagram
    participant Main Program
    participant File Processor Subroutine
    participant Transaction File
    participant CrossReference File
    participant Customer File
    participant Account File

    activate Main Program
    Main Program->>+File Processor Subroutine: Open Transaction File
    activate File Processor Subroutine
    File Processor Subroutine->>+Transaction File: Open
    Transaction File->>File Processor Subroutine: Open Successful
    File Processor Subroutine->>Main Program: File Opened Successfully

    Main Program->>+File Processor Subroutine: Read Transaction Record
    File Processor Subroutine->>+Transaction File: Read Record
    Transaction File->>File Processor Subroutine: Transaction Record Data
    File Processor Subroutine->>Main Program: Transaction Record Data

    Main Program->>+File Processor Subroutine: Open Customer File with Customer ID
    File Processor Subroutine->>+Customer File: Open
    Customer File->>File Processor Subroutine: Open Successful
    File Processor Subroutine->>Main Program: File Opened Successfully
    Main Program->>+File Processor Subroutine: Read Customer Record with Customer ID
    File Processor Subroutine->>+Customer File: Read Record
    Customer File->>File Processor Subroutine: Customer Record Data
    File Processor Subroutine->>Main Program: Customer Record Data

    Main Program->>+File Processor Subroutine: Open Account File with Account ID
    File Processor Subroutine->>+Account File: Open
    Account File->>File Processor Subroutine: Open Successful
    File Processor Subroutine->>Main Program: File Opened Successfully
    Main Program->>+File Processor Subroutine: Read Account Record with Account ID
    File Processor Subroutine->>+Account File: Read Record
    Account File-->>-File Processor Subroutine: Account Record Data
    File Processor Subroutine->>Main Program: Account Record Data
    
    Main Program->>+File Processor Subroutine: Close Transaction File
    File Processor Subroutine->>+Transaction File: Close
    Transaction File->>File Processor Subroutine: Close Successful
    deactivate Transaction File
    File Processor Subroutine->>Main Program: File Closed Successfully

    Main Program->>+File Processor Subroutine: Close Customer File
    File Processor Subroutine->>+Customer File: Close
    Customer File->>File Processor Subroutine: Close Successful
    deactivate Customer File
    File Processor Subroutine-->>-Main Program: File Closed Successfully

    Main Program->>+File Processor Subroutine: Close Account File
    File Processor Subroutine->>+Account File: Close
    Account File->>File Processor Subroutine: Close Successful
    deactivate Account File
    File Processor Subroutine->>Main Program: File Closed Successfully
    deactivate File Processor Subroutine
    deactivate Main Program