sequenceDiagram
    %%Indicates the Participants involved in the process
    participant User
    participant COBIL00C
    participant ACCTDAT
    participant CXACAIX
    participant TRANSACT

    activate User
    User->>+COBIL00C: Input Account ID and Payment Confirmation
    activate COBIL00C
    COBIL00C->>+ACCTDAT: Read Account Balance
    activate ACCTDAT
    ACCTDAT->>COBIL00C: Account Balance
    deactivate ACCTDAT
    COBIL00C->>+CXACAIX: Read Card Details
    activate CXACAIX
    CXACAIX->>COBIL00C: Card Details
    deactivate CXACAIX
    COBIL00C->>+TRANSACT: Generate Transaction ID
    activate TRANSACT
    TRANSACT->>COBIL00C:  New Transaction ID
    deactivate TRANSACT
    COBIL00C->>+TRANSACT: Write Transaction Details
    activate TRANSACT
    TRANSACT->>COBIL00C:  Transaction Recorded
    deactivate TRANSACT
    COBIL00C->>+ACCTDAT: Update Account Balance
    activate ACCTDAT
    ACCTDAT->>COBIL00C: Account Balance Updated
    deactivate ACCTDAT
    COBOL00C->>User: Payment Confirmation with Transaction ID
    deactivate COBIL00C
    deactivate User