sequenceDiagram
    participant CustomerServiceRepresentative
    participant COCRDSLC
    participant CARDDAT

    activate CustomerServiceRepresentative
    CustomerServiceRepresentative->>+COCRDSLC: Enter Account/Card Number
    COCRDSLC->>+CustomerServiceRepresentative: Display Screen
    CustomerServiceRepresentative->>+COCRDSLC: Submit Input
    COCRDSLC->>+COCRDSLC: Validate Input Data
    alt Input Valid
        COCRDSLC->>+CARDDAT: Search for Matching Record
        alt Record Found
            CARDDAT->>COCRDSLC: Return Credit Card Details
            COCRDSLC->>CustomerServiceRepresentative: Display Credit Card Details
        else Record Not Found
            CARDDAT->>-COCRDSLC: Return Not Found Error
            COCRDSLC->>CustomerServiceRepresentative: Display Error Message 
        end
    else Input Invalid
        COCRDSLC->>-CustomerServiceRepresentative: Display Error Message
    end
    deactivate CustomerServiceRepresentative