sequenceDiagram
    %%Indicates the Participants involved in the process
    participant User
    participant COSGN00C
    participant USRSEC File
    participant COADM01C
    participant COMEN01C

    User->>+COSGN00C: Enters User ID and Password
    COSGN00C->>+USRSEC File: Read User Data
    USRSEC File-->>-COSGN00C: User Data (User ID, Password, User Type)
    
    alt User ID and Password Valid
        COSGN00C->>COSGN00C: Determine User Type
        alt User Type is Administrator
            COSGN00C->>+COADM01C: Transfer Control
            COADM01C-->>COSGN00C: Display Administrator Menu
        else User Type is Regular User
            COSGN00C->>+COMEN01C: Transfer Control
            COMEN01C-->>COSGN00C: Display Main Menu
        end
    else User ID or Password Invalid
        COSGN00C->>-User: Display Error Message 
    end