sequenceDiagram
    participant CallingProgram
    participant CSUTLDTC
    participant CEEDAYS

    activate CallingProgram
    CallingProgram->>+CSUTLDTC: Date, Date Format
    activate CSUTLDTC
    CSUTLDTC->>+CEEDAYS: Date, Date Format
    activate CEEDAYS
    alt Date Format is Valid
        CEEDAYS->>CSUTLDTC: Lilian Date or Error Code
    else Date Format is Invalid
        CEEDAYS->>CSUTLDTC:  Error Code 'Bad Pic String '
    end
    deactivate CEEDAYS
    CSUTLDTC->>CallingProgram: Lilian Date or Error Message
    deactivate CSUTLDTC
    deactivate CallingProgram