sequenceDiagram
    participant Administrator
    participant COADM02Y
    participant COUSR00C
    participant COUSR01C
    participant COUSR02C
    participant COUSR03C
    
    activate Administrator
    Administrator->>+COADM02Y: Select Option (List,Add,Update,Delete)
    activate COADM02Y
    COADM02Y->>-Administrator: Display User Management Menu
    Administrator->>+COADM02Y: Select Option (User List)
    COADM02Y->>+COUSR00C: Call User List Program
    activate COUSR00C
    COUSR00C->>COADM02Y: Return User List
    deactivate COUSR00C
    COADM02Y->>Administrator: Display User List
    deactivate Administrator
    deactivate COADM02Y