sequenceDiagram
    participant Program A
    participant Communication Area
    participant Program B

    activate Program A
    Program A->>+Communication Area: Store Data
    deactivate Program A
    activate Communication Area
    Communication Area->>Program A: Data Stored
    deactivate Communication Area

    activate Program B
    Program B->>+Communication Area: Retrieve Data
    deactivate Program B
    activate Communication Area
    Communication Area->>Program B: Data Retrieved
    deactivate Communication Area