sequenceDiagram
    participant User
    participant CardDemo Application

    activate CardDemo Application
    CardDemo Application->>+User: Display Title (AWS Mainframe Modernization)
    CardDemo Application->>User: Display Title (CardDemo)

    User->>+CardDemo Application: Use Application
    CardDemo Application->>-User: Application Display

    User->>+CardDemo Application: Exit Application
    CardDemo Application->>+User: Display Thank You Message
    deactivate CardDemo Application
    deactivate User