sequenceDiagram
    %%Indicates the Participants involved in the process
    participant User
    participant CardDemo Application
    participant Data Validation Logic
    participant Screen Display

    activate User
    User->>+CardDemo Application: Enters Data
    activate CardDemo Application
    CardDemo Application->>+Data Validation Logic: Validate Input (TESTVAR1)
    activate Data Validation Logic
    alt TESTVAR1 is Invalid
        Data Validation Logic->>CardDemo Application: Validation Error
        CardDemo Application->>+Screen Display: Highlight Field (SCRNVAR2) in Red
                    else TESTVAR1 is Blank
        Data Validation Logic->>CardDemo Application: Blank Field Detected
        CardDemo Application->>+Screen Display: Display Asterisk (*) in Field (SCRNVAR2)
                    else TESTVAR1 is Valid
        Data Validation Logic->>CardDemo Application: Validation Successful
        deactivate Data Validation Logic
        deactivate CardDemo Application
    end
    deactivate User