sequenceDiagram
    %%Indicates the Participants involved in the process
    participant Card Validation Program
    participant Input File
    participant Output File
    participant Error Log

    activate Card Validation Program
    Card Validation Program->>+Input File: Open
    Input File->>Card Validation Program: Open Successful
    
    loop For Each Record in Input File
        Card Validation Program->>+Input File: Read Record
        Input File->>Card Validation Program: Card Record Data
    
        alt Validation Successful
            Card Validation Program->>+Output File: Write Record
            Output File->>Card Validation Program: Write Successful
        else Validation Failed
            Card Validation Program->>+Error Log: Write Error
            Error Log-->>-Card Validation Program: Write Successful
        end
    end

    Card Validation Program->>+Input File: Close
    Input File->>Card Validation Program: Close Successful
    Card Validation Program->>+Output File: Close
    Output File->>-Card Validation Program: Close Successful
    deactivate Card Validation Program