sequenceDiagram
    %%Indicates the Participants involved in the process
    participant Transaction Processing System
    participant COTRN02 Copybook
    participant Transaction Data File

    activate Transaction Processing System
    Transaction Processing System->>+COTRN02 Copybook: Load Data Structure
    COTRN02 Copybook-->>-Transaction Processing System: Data Structure Loaded

    Transaction Processing System->>+Transaction Data File: Open
    Transaction Data File->>Transaction Processing System: File Opened

    loop For Each Transaction
        Transaction Processing System->>+Transaction Data File: Write Transaction Record
        Transaction Data File->>Transaction Processing System: Record Written
    end

    Transaction Processing System->>+Transaction Data File: Close
    Transaction Data File->>-Transaction Processing System: File Closed
    deactivate Transaction Processing System