sequenceDiagram
    participant User
    participant ApplicationProgram
    participant CORPT00CPY

    activate ApplicationProgram
    ApplicationProgram->>+User: Request Corporate Data Input
    User-->>-ApplicationProgram: Provide Corporate Data
    ApplicationProgram->>+CORPT00CPY: Access Data Structures
    activate CORPT00CPY
    CORPT00CPY->>ApplicationProgram: Data Structures Definitions
    deactivate CORPT00CPY
    ApplicationProgram->>ApplicationProgram: Process and Store Data
    deactivate ApplicationProgram