sequenceDiagram
    %%Indicates the Participants involved in the process
    participant Program
    participant InputFile
    participant ValidOutputFile
    participant ErrorLogFile

    activate Program
    Program->>+InputFile: Open
    InputFile-->>-Program: Open Successful

    Program->>+ErrorLogFile: Open
    ErrorLogFile-->>-Program: Open Successful    

    loop For Each Customer Record
        Program->>+InputFile: Read Record
        InputFile-->>-Program: Customer Record Data        
        activate Program
        Program->>Program: Validate Customer ID
        alt Customer ID is Valid            
            Program->>Program: Validate Data Types
            alt Data Types are Valid
                Program->>Program: Validate Data Length
                alt Data Length is Valid
                    Program->>Program: Validate Data Format
                    alt Data Format is Valid
                        Program->>+ValidOutputFile: Write Record
                        ValidOutputFile-->>-Program: Write Successful
                    else Data Format is Invalid
                        Program->>+ErrorLogFile: Write Error
                        ErrorLogFile-->>-Program: Write Successful
                                            end                        
                else Data Length is Invalid
                    Program->>+ErrorLogFile: Write Error
                    ErrorLogFile-->>-Program: Write Successful
                                    end
            else Data Types are Invalid
                Program->>+ErrorLogFile: Write Error
                ErrorLogFile-->>-Program: Write Successful
                            end            
        else Customer ID is Invalid
            Program->>+ErrorLogFile: Write Error
            ErrorLogFile-->>-Program: Write Successful
                    end
    end
    
    Program->>+ValidOutputFile: Close
    ValidOutputFile->>-Program: Close Successful

    Program->>+ErrorLogFile: Close
    ErrorLogFile->>-Program: Close Successful
    
    deactivate Program