sequenceDiagram
    %%Indicates the Participants involved in the process
    participant CardXRefProcessor
    participant CardXRefFile
    participant ErrorLogFile
    participant ReportFile

    activate CardXRefProcessor

    CardXRefProcessor->>+CardXRefFile: Open
    CardXRefFile-->>-CardXRefProcessor: Open Successful

    loop For Each Line in File
        CardXRefProcessor->>+CardXRefFile: Read Record
        CardXRefFile-->>-CardXRefProcessor: Card Data

        alt Card Data is Valid
            CardXRefProcessor->>+ReportFile: Write Record
            ReportFile-->>-CardXRefProcessor: Write Successful
        else Card Data is Invalid
            CardXRefProcessor->>+ErrorLogFile: Write Error
            ErrorLogFile-->>-CardXRefProcessor: Write Successful
        end
    end

    CardXRefProcessor->>+CardXRefFile: Close
    CardXRefFile->>-CardXRefProcessor: Close Successful
    CardXRefProcessor->>+ErrorLogFile: Close
    ErrorLogFile->>-CardXRefProcessor: Close Successful
    CardXRefProcessor->>+ReportFile: Close
    ReportFile->>-CardXRefProcessor: Close Successful

    deactivate CardXRefProcessor