sequenceDiagram
  %%Indicates the Participants involved in the process
  participant System Administrator
  participant Configuration System
  participant Disk Storage

  activate System Administrator
  System Administrator->>+Configuration System: Update discgrp.txt
  deactivate System Administrator

  activate Configuration System
  Configuration System->>+Disk Storage: Open discgrp.txt
  Disk Storage->>Configuration System: discgrp.txt Opened
  
  loop For Each Line in discgrp.txt
    Configuration System->>+Disk Storage: Read Line
    Disk Storage->>Configuration System: Group ID and Configuration Settings
    Configuration System->>Configuration System: Parse and Validate Data
    alt Valid Configuration
        Configuration System->>Configuration System: Apply Configuration
    else Invalid Configuration
        Configuration System->>Configuration System: Log Error 
    end    
  end
  Configuration System->>+Disk Storage: Close discgrp.txt
  Disk Storage->>-Configuration System: discgrp.txt Closed
  deactivate Configuration System