sequenceDiagram
    participant User
    participant Application
    participant TransactionCodeTable

    activate Application
    User->>+Application: Input Transaction Code
    Application->>+TransactionCodeTable: Lookup Transaction Code
    alt Transaction Code Found
        TransactionCodeTable->>Application: Return Transaction Description
        Application->>User: Display Transaction Description
    else Transaction Code Not Found
        TransactionCodeTable->>-Application: Return Error
        Application->>User: Display Error Message
    end
    deactivate Application